# Generated by Django 3.1.7 on 2021-04-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='musicgenre',
            field=models.CharField(choices=[('Hiphop', 'Hiphop'), ('Rap', 'Rap'), ('Jazz', 'Jazz'), ('Techno', 'Techno'), ('R & B', 'Rb'), ('Punk', 'Punk'), ('Rock', 'Rock'), ('Alternative', 'Alternative'), ('Metal', 'Metal'), ('Country', 'Country'), ('Indie', 'Indie'), ('EDM', 'Edm'), ('Booty Bass', 'Bootybass')], default='Booty Bass', max_length=100),
        ),
    ]
