# Generated by Django 3.1.7 on 2021-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210404_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='musicgenre',
            field=models.CharField(choices=[('Hiphop', 'Hip-hop'), ('Rap', 'Rap'), ('Jazz', 'Jazz'), ('Techno', 'Techno'), ('R & B', 'R & B'), ('Punk', 'Punk'), ('Rock', 'Rock'), ('Alternative', 'Alternative'), ('Metal', 'Metal'), ('Country', 'Country'), ('Indie', 'Indie'), ('EDM', 'EDM'), ('Booty Bass', 'Booty Bass'), ('gossip', 'Gossip'), ('Other', 'Other')], default='Booty Bass', max_length=100),
        ),
    ]
