# Generated by Django 3.1.7 on 2021-04-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='musicgenre',
            field=models.CharField(max_length=100),
        ),
    ]
