# Generated by Django 3.1.7 on 2021-04-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0002_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
