# Generated by Django 3.1.7 on 2021-04-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0003_auto_20210401_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
